AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template launches an EC2 instance which enables SSH.
  
Resources:
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: LOGO
      SecurityGroups: 
        - ssh-http
      Tags:
        - Key: Name
          Value: Web Server of StackName
      UserData:  
        Fn::Base64:
          !Sub |
            #! /bin/bash

            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/serdarcw/my-repository/master/Project-101-kittens-carousel-static-website-ec2/static-web"
            cd /var/www/html
            wget $FOLDER/index.html
            wget $FOLDER/cat0.jpg
            wget $FOLDER/cat1.jpg
            wget $FOLDER/cat2.jpg
            wget $FOLDER/cat3.png
            systemctl start httpd
            systemctl enable httpd
      Outputs:
         WebsiteURL: 
          Value: !Sub 
            - http://${PublicAddress}
            - PublicAddress: !GetAtt WebServerHost.PublicDnsName
          Description: Kittens Carousel Application URL